[package]
name = "nom-syslog"
version = "0.1.0"
authors = ["hmarshall <hunter.marshall@viasat.com>", "Xavier Lange <xrlange@gmail.com>"]

[lib]
name = "nom_syslog"

[dependencies]
nom = "3.2"
time = "0.1"